on: [pull_request]
name: test
jobs:
  test:
    name: ${{ matrix.toolchain }} (${{ matrix.profile.name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: miri, rust-src
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --manifest-path ${{ matrix.manifest-path }} ${{ matrix.profile.flag }}
      - uses: actions-rs/cargo@v1
        name: cargo miri setup
        with:
          command: miri
          args: setup
      - uses: actions-rs/cargo@v1
        name: cargo miri test
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation"
        with:
          command: miri
          args: test --manifest-path ${{ matrix.manifest-path }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
        features:
          - asm
        profile:
          - name: debug
          - name: release
            flag: --release
        manifest-path:
          - Cargo.toml
          - src/v2/Cargo.toml
