on: [pull_request]
name: test
jobs:
  test:
    name: ${{ matrix.toolchain }} (${{ matrix.profile.name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.profile.flag }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
          - stable
          - 1.57.0
        features:
          -
        profile:
          - name: debug
          - name: release
            flag: --release
        include:
          - toolchain: nightly
            features: asm
            profile: {name: debug}
          - toolchain: nightly
            features: asm
            profile: {name: release, flag: --release}
